version: 0.0.{build}
image: Visual Studio 2017
configuration: Release
for:
  -
    branches:
      only:
        - master
  build_script:
    - ps: .\BuildScript\build.ps1 -Script BuildScript/build.cake -ScriptArgs '--shouldPublish="True"'

  -
    branches:
        only:
          - develop
    build_script:
      - ps: .\BuildScript\build.ps1 -Script BuildScript/build.cake -ScriptArgs '--shouldPublish="False"'
test: off
deploy: off