version: 0.0.{build}
image: Visual Studio 2019
configuration: Release
for:
  -
    branches:
      only:
        - master
    build_script:
      - ps: .\build.ps1 --target PushNugetPackages
  -
    branches:
      except:
        - master
    build_script:
      - ps: .\build.ps1 --target RunUnitTests
test: off
deploy: off